#180: add exit and help cmds
genjidb/genji pull request #239
Opened 2020-10-08 04:08 UTC by ab22

## Description

Changes for issue #180 

The `help` and `exit` commands work correctly when typing them, however, when typing the new commands the suggestions list won't show up and this is because of the way their [previous commands were added](https://github.com/ab22/genji/blob/master/cmd/genji/shell/command.go#L21-L22).

Also, when typing `.help` or `.exit` it now displays `.help or help` or `.exit or exit` on the suggestions. I am wondering how would you like these commands to be added to the suggestion list. Maybe an `alias []string` under the `commands` structure?

2020-10-09 03:50 UTC, ab22 commented
Would you guys like me to propose code changes to correctly support the new command suggestions correctly? @asdine

2020-10-09 06:00 UTC, asdine commented
@ab22 Thanks for taking care of this!

> Maybe an alias []string under the commands structure?

I think this is a good idea

2020-10-09 22:50 UTC, ab22 commented on cmd/genji/shell/command.go
> +		return fmt.Errorf("unknown command %q. Enter \".help\" for help", in)
This fixes a go-lint issue: `error strings should not be capitalized or end with punctuation or a newline`

2020-10-09 23:03 UTC, ab22 commented
I went ahead and added a small command builder. This way we add a little more flexibility for the commands in the future, for example if we wanted to add individual options instead of just a string, then this would easily perform validations when building it.

2020-10-10 06:30 UTC, asdine commented on cmd/genji/shell/command.go
> +	newCommandBuilder(".exit").
This feels very Java-esque, I feel the same can be achieved by filling the struct directly:

```go
var commands = []*command{
  {
    name: ".exit",
    aliases: []string{"exit"},
    description: "Exit this program.",
  },
  {
    name: ".help",
    aliases: []string{"help"},
    description: "List all commands.",
  },
}

type command struct {
	Name        string
	Options     string
	DisplayName string
	Description string
}

func (c *command) String() string {
  ...
}
```

2020-10-12 09:36 UTC, asdine requested changes
Thanks @ab22, this looks good, I just have a few nitpicking comments

2020-10-12 09:36 UTC, asdine commented on cmd/genji/shell/command.go
> +		Options:     "",
nit: You don't have to do this in Go, non initialized fields are equal to the [zero value of their type](https://www.geeksforgeeks.org/zero-value-in-golang/)

```suggestion
```

2020-10-12 09:36 UTC, asdine commented on cmd/genji/shell/command.go
> +		Aliases:     []string{},
Same here, you can remove this line

2020-10-12 16:05 UTC, ab22 commented
Hey @asdine, sure, no problem. I left those out because of how they were previously declared. Just forced pushed a commit to remove those lines. :D

2020-10-12 16:39 UTC, asdine approved these changes
Thank you @ab22 !

2020-10-12 16:40 UTC, merged